In [1]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd
import os


df_men = pd.read_csv("bcci_men_odi_stats.csv")
df_women = pd.read_csv("bcci_women_odi_stats.csv")


df_men["Gender"] = "Men"
df_women["Gender"] = "Women"

# Step 3: Combine them
df_combined = pd.concat([df_men, df_women], ignore_index=True)

# Step 4: Create Sachin’s record
sachin_row = pd.DataFrame([{
    "Player": "Sachin Tendulkar",
    "Matches": 463,
    "Innings": 452,
    "Average": 44.83,
    "SR": 86.23,
    "HS": 200,
    "4s": 2016,
    "6s": 195,
    "50s": 96,
    "100s": 49,
    "Runs": 18426,
    "Gender": "Men"
}])

# Step 5: Add him at the top
df_combined = pd.concat([sachin_row, df_combined], ignore_index=True)

# Step 6: Verify
print(df_combined.head(5))
print("Total rows:", len(df_combined))

# Step 7: Save it again
#df_combined.to_csv("bcci_combined_odi_stats.csv", index=False)

             Player  Matches  Innings  Average     SR   HS    4s   6s 50s  \
0  Sachin Tendulkar      463      452    44.83  86.23  200  2016  195  96   
1       Virat Kohli      305      293    57.71  93.26  183  1332  152  75   
2      Rohit Sharma      276      268    49.22  92.66  264  1066  349  59   
3    Sourav Ganguly      311      300    41.02   73.7  183  1122  190  72   
4      Rahul Dravid      344      318    39.16  71.23  153   950   42  83   

  100s   Runs Gender  
0   49  18426    Men  
1   51  14255    Men  
2   33  11370    Men  
3   22  11363    Men  
4   12  10889    Men  
Total rows: 372


In [3]:
df_combined.shape

(372, 12)

In [4]:
df_combined

Player  Matches  Innings  Average     SR   HS    4s   6s 50s  \
0     Sachin Tendulkar      463      452    44.83  86.23  200  2016  195  96   
1          Virat Kohli      305      293    57.71  93.26  183  1332  152  75   
2         Rohit Sharma      276      268    49.22  92.66  264  1066  349  59   
3       Sourav Ganguly      311      300    41.02   73.7  183  1122  190  72   
4         Rahul Dravid      344      318    39.16  71.23  153   950   42  83   
..                 ...      ...      ...      ...    ...  ...   ...  ...  ..   
367  Bindeshwari Goyal        4        1     0.00     25    1     -    -   -   
368   Samantha Lobatto        3        2     0.00   12.5    1     -    -   -   
369      Anjali Sharma        3        3     0.33      -    1     -    -   -   
370         Rita Patel        1        1     1.00      -    1     -    -   -   
371      Manju Nadgoda        1        1     1.00   7.69    1     -    -   -   

    100s   Runs Gender  
0     49  18426    Men  
1     51  14255    Men  
2     33  11370    Men  
3     22  11363    Men  
4     12  10889    Men  
..   ...    ...    ...  
367    -      1  Women  
368    -      1  Women  
369    -      1  Women  
370    -      1  Women  
371    -      1  Women  

[372 rows x 12 columns]

In [5]:
# Step 7: Save it again
df_combined.to_csv("bcci_combined_odi_stats.csv", index=False)

### Data Cleaning

In [6]:
df_combined.columns

Index(['Player', 'Matches', 'Innings', 'Average', 'SR', 'HS', '4s', '6s',
       '50s', '100s', 'Runs', 'Gender'],
      dtype='object')

In [7]:
dataset=pd.read_csv("bcci_combined_odi_stats.csv")
dataset

Player  Matches  Innings  Average     SR   HS    4s   6s 50s  \
0     Sachin Tendulkar      463      452    44.83  86.23  200  2016  195  96   
1          Virat Kohli      305      293    57.71  93.26  183  1332  152  75   
2         Rohit Sharma      276      268    49.22  92.66  264  1066  349  59   
3       Sourav Ganguly      311      300    41.02   73.7  183  1122  190  72   
4         Rahul Dravid      344      318    39.16  71.23  153   950   42  83   
..                 ...      ...      ...      ...    ...  ...   ...  ...  ..   
367  Bindeshwari Goyal        4        1     0.00     25    1     -    -   -   
368   Samantha Lobatto        3        2     0.00   12.5    1     -    -   -   
369      Anjali Sharma        3        3     0.33      -    1     -    -   -   
370         Rita Patel        1        1     1.00      -    1     -    -   -   
371      Manju Nadgoda        1        1     1.00   7.69    1     -    -   -   

    100s   Runs Gender  
0     49  18426    Men  
1     51  14255    Men  
2     33  11370    Men  
3     22  11363    Men  
4     12  10889    Men  
..   ...    ...    ...  
367    -      1  Women  
368    -      1  Women  
369    -      1  Women  
370    -      1  Women  
371    -      1  Women  

[372 rows x 12 columns]

In [8]:
dataset.columns

Index(['Player', 'Matches', 'Innings', 'Average', 'SR', 'HS', '4s', '6s',
       '50s', '100s', 'Runs', 'Gender'],
      dtype='object')

In [9]:
dataset=dataset.rename(columns={'Player':'PlayerName',
                               'SR':'StrikeRate',
                               'HS':'HighestScore',})

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PlayerName    372 non-null    object 
 1   Matches       372 non-null    int64  
 2   Innings       372 non-null    int64  
 3   Average       372 non-null    float64
 4   StrikeRate    372 non-null    object 
 5   HighestScore  372 non-null    int64  
 6   4s            372 non-null    object 
 7   6s            372 non-null    object 
 8   50s           372 non-null    object 
 9   100s          372 non-null    object 
 10  Runs          372 non-null    int64  
 11  Gender        372 non-null    object 
dtypes: float64(1), int64(4), object(7)
memory usage: 35.0+ KB


In [11]:
dataset[dataset['PlayerName']=='-']

PlayerName  Matches  Innings  Average StrikeRate  HighestScore 4s 6s 50s  \
128          -       23       12     10.0      59.25            28  4  -   -   

    100s  Runs Gender  
128    -    80    Men

In [12]:
dataset=dataset.drop(index=128)

In [13]:
dataset

PlayerName  Matches  Innings  Average StrikeRate  HighestScore  \
0     Sachin Tendulkar      463      452    44.83      86.23           200   
1          Virat Kohli      305      293    57.71      93.26           183   
2         Rohit Sharma      276      268    49.22      92.66           264   
3       Sourav Ganguly      311      300    41.02       73.7           183   
4         Rahul Dravid      344      318    39.16      71.23           153   
..                 ...      ...      ...      ...        ...           ...   
367  Bindeshwari Goyal        4        1     0.00         25             1   
368   Samantha Lobatto        3        2     0.00       12.5             1   
369      Anjali Sharma        3        3     0.33          -             1   
370         Rita Patel        1        1     1.00          -             1   
371      Manju Nadgoda        1        1     1.00       7.69             1   

       4s   6s 50s 100s   Runs Gender  
0    2016  195  96   49  18426    Men  
1    1332  152  75   51  14255    Men  
2    1066  349  59   33  11370    Men  
3    1122  190  72   22  11363    Men  
4     950   42  83   12  10889    Men  
..    ...  ...  ..  ...    ...    ...  
367     -    -   -    -      1  Women  
368     -    -   -    -      1  Women  
369     -    -   -    -      1  Women  
370     -    -   -    -      1  Women  
371     -    -   -    -      1  Women  

[371 rows x 12 columns]

In [14]:
dataset[dataset['PlayerName']=='-'] # there no missing values in names

Empty DataFrame
Columns: [PlayerName, Matches, Innings, Average, StrikeRate, HighestScore, 4s, 6s, 50s, 100s, Runs, Gender]
Index: []

In [15]:
dataset.columns

Index(['PlayerName', 'Matches', 'Innings', 'Average', 'StrikeRate',
       'HighestScore', '4s', '6s', '50s', '100s', 'Runs', 'Gender'],
      dtype='object')

In [16]:
dataset[dataset['Matches']=='-'] # There are no Missing values in matches

Empty DataFrame
Columns: [PlayerName, Matches, Innings, Average, StrikeRate, HighestScore, 4s, 6s, 50s, 100s, Runs, Gender]
Index: []

In [17]:
dataset.columns

Index(['PlayerName', 'Matches', 'Innings', 'Average', 'StrikeRate',
       'HighestScore', '4s', '6s', '50s', '100s', 'Runs', 'Gender'],
      dtype='object')

In [18]:
dataset['Matches'].unique() #There are no records where players have 0 matches or missing match data(Like Nan)

array([463, 305, 276, 311, 344, 350, 334, 304, 251, 167, 226, 196, 147,
       136, 146, 225, 129, 150, 108,  88,  90,  73,  58, 204, 125, 104,
        86,  74,  85,  94, 130,  55, 120, 140, 191, 236,  57,  45, 271,
        46,  27, 229,  42,  31,  40,  71, 200,  32,  37,  38, 116,  24,
        72,  69,  29, 121,  16,  20,  65,  25,  67,  49,  34,  26,  17,
        47,  39,  68,  36,  12,  18,  15,  23,  10,  14, 161,  19, 114,
        13,   7,   6,  11,  35,   5,  30,   2,   8,   3,  89,  75,  70,
        80,  22,   4,   1,  59,  53,   9, 232, 117, 127,  77,  51,  78,
        44,  48,  28,  33,  21,  41,  43,  63,  50,  97,  64])

In [19]:
dataset['Matches'].isna().sum()

np.int64(0)

In [20]:
dataset['Innings'].unique()

array([452, 293, 268, 300, 318, 297, 308, 278, 245, 164, 194, 179, 143,
       127, 145, 198, 120, 128, 102,  81,  87,  67,  58, 137, 110,  97,
        83,  70,  75,  68,  98,  79,  50,  52,  96, 113,  51,  42, 136,
        24, 121,  40,  27,  36,  49,  41, 101,  31,  35,  34,  63,  45,
        65,  55,  30,  14,  19,  23,  17,  16,  25,  26,  33,  12,  21,
         9,  11,   8,  15,   7,   6,  10,  46,  18,   4,  13,   2,   5,
        20,   3,  28,   1, 211, 117, 140, 112, 103,  73,  56,  59,  60,
        37,  29,  22])

In [21]:
dataset['Average'].unique()

array([44.83, 57.71, 49.22, 41.02, 39.16, 50.57, 36.92, 36.55, 35.05,
       44.11, 35.31, 37.47, 39.68, 37.08, 29.01, 23.79, 34.73, 29.04,
       35.13, 48.31, 35.26, 47.81, 56.36, 32.62, 32.01, 32.59, 30.76,
       33.23, 30.53, 32.82, 24.12, 30.2 , 47.05, 23.39, 42.09, 20.19,
       14.58, 13.3 , 27.95, 24.51, 10.54, 25.94, 42.4 , 10.63, 28.48,
       33.5 , 33.34, 23.18, 27.  , 12.  , 25.76, 23.74, 16.44, 28.08,
       16.12, 23.73, 17.17, 33.29, 13.09, 14.15, 20.52, 56.66, 30.46,
       24.  , 19.95, 19.09, 20.72, 15.73, 21.93, 17.84, 21.18, 17.31,
       15.5 , 13.9 , 20.71, 26.09, 25.45, 20.69, 23.27, 30.37, 28.75,
        7.75, 31.85,  6.9 , 24.22, 16.61,  9.85, 33.83, 27.57, 31.5 ,
       13.84, 22.  , 18.33, 11.64, 22.57, 25.5 , 21.85, 18.87, 13.54,
        5.64, 27.2 , 10.15, 14.55, 65.  , 14.  ,  9.38, 11.8 , 11.6 ,
       19.16, 57.5 , 11.4 , 38.  , 53.5 , 10.4 , 33.33, 31.  ,  7.58,
       12.85, 12.57,  9.55, 17.2 , 20.25, 13.5 ,  7.9 , 15.8 ,  8.55,
        6.72, 36.5 ,

In [22]:
dataset['StrikeRate'].unique() #miissing values in sr section

array(['86.23', '93.26', '92.66', '73.7', '71.23', '87.56', '74.02',
       '87.67', '104.33', '91.35', '93.5', '69.79', '85.25', '69.72',
       '71.74', '95.07', '67.74', '61.07', '62.26', '88.41', '78.63',
       '99.01', '99.22', '85.44', '72.03', '71.94', '64.3', '57.7',
       '110.89', '60.26', '73.24', '79.04', '79.54', '101.6', '68.94',
       '80.62', '81.06', '71.47', '82.17', '90.59', '102.19', '79.62',
       '63.02', '106.21', '73.47', '91.76', '113.6', '73.46', '67.15',
       '105.02', '76.5', '86.96', '59.15', '60.13', '55.63', '89.43',
       '90.56', '69.67', '73.89', '64.2', '99.6', '70.85', '90.47',
       '52.89', '90.4', '62.17', '60.55', '64.64', '83.97', '66.21',
       '66.99', '105.11', '62.24', '88.21', '72.5', '71.21', '73.49',
       '67.25', '52.84', '60.8', '60.9', '93.49', '82.41', '90.65',
       '60.21', '60.05', '80.89', '50.85', '98.06', '58.3', '113.85',
       '75.31', '66.41', '49.69', '62.69', '86.33', '47.73', '80.95',
       '50.83', '64.52', 

In [23]:
dataset['StrikeRate']=pd.to_numeric(dataset['StrikeRate'].replace('-',np.nan),errors='coerce') 
#filled -,whitespaces with nans because sr cannot repalce with zero 
#coerce repaces anything that is not a number with nan

In [24]:
dataset['StrikeRate']=dataset['StrikeRate'].astype(float)

In [25]:
dataset['StrikeRate'].dtype

dtype('float64')

In [26]:
dataset['HighestScore'].unique()

array([200, 183, 264, 153, 150, 219, 143, 116, 119, 134, 123, 175, 105,
       109, 103, 112, 111, 128, 208,  87, 106, 131, 102,  92,  79, 124,
        83, 120,  69,  95,  49, 159,  84,  26,  86, 210,  53,  89, 125,
       100,  64,  34,  72,  65,  82,  57, 114,  61, 104,  42, 108, 101,
        75,  59,  48,  55,  51,  50,  54,  33,  67,  39,  78,  94,  77,
        25,  46,  19,  56,  24,  41,  32,  63,  58,  21,  31,  71,  20,
        45,  23,  62,  70,  16,  30,  27,  18,  15,  13,  52,   9,  38,
         8,  37,  10,  44,  14,  29,  11,   7,  22,  12,   5,   6,   4,
         3,   2,   1, 136, 171, 188, 138, 127,  90,  96, 154, 115, 113,
        80,  47,  97,  88,  68,  35,  17])

In [27]:
dataset['4s'] = pd.to_numeric(dataset['4s'], errors='coerce').astype('Int64')

In [28]:
dataset['4s'].dtype

Int64Dtype()

In [29]:
dataset['4s'].isna().sum()

np.int64(117)

In [30]:
dataset['6s'] = pd.to_numeric(dataset['6s'], errors='coerce').astype('Int64')

In [31]:
dataset['6s'].dtype

Int64Dtype()

In [32]:
dataset['6s'].isna().sum()

np.int64(217)

In [33]:
dataset.columns

Index(['PlayerName', 'Matches', 'Innings', 'Average', 'StrikeRate',
       'HighestScore', '4s', '6s', '50s', '100s', 'Runs', 'Gender'],
      dtype='object')

In [34]:
dataset['50s'].unique() # there is '-' for some records we need to assign it 0

array(['96', '75', '59', '72', '83', '73', '58', '52', '38', '39', '36',
       '30', '34', '33', '27', '14', '23', '18', '24', '15', '13', '17',
       '10', '11', '9', '5', '6', '2', '3', '-', '4', '7', '1', '64',
       '22', '8', '12'], dtype=object)

In [35]:
dataset['50s'] = pd.to_numeric(dataset['50s'].replace('-', 0), errors='coerce').fillna(0)

In [36]:
dataset['50s']=dataset['50s'].astype(int)

In [37]:
dataset['50s'].dtypes

dtype('int64')

In [38]:
dataset['50s'].unique()

array([96, 75, 59, 72, 83, 73, 58, 52, 38, 39, 36, 30, 34, 33, 27, 14, 23,
       18, 24, 15, 13, 17, 10, 11,  9,  5,  6,  2,  3,  0,  4,  7,  1, 64,
       22,  8, 12])

In [39]:
#Replacing '-' values with null
dataset['50s']=dataset['50s'].replace('-',0)

In [40]:
dataset['50s'].dtypes

dtype('int64')

In [41]:
dataset['100s'].unique()

array(['49', '51', '33', '22', '12', '10', '7', '14', '15', '17', '5',
       '6', '11', '4', '1', '3', '8', '-', '2'], dtype=object)

In [42]:
dataset['100s']=dataset['100s'].replace('-',0)

In [43]:
dataset['100s'].unique()

array(['49', '51', '33', '22', '12', '10', '7', '14', '15', '17', '5',
       '6', '11', '4', '1', '3', '8', 0, '2'], dtype=object)

In [44]:
dataset['100s']=dataset['100s'].astype(int)

In [45]:
dataset['100s'].dtype

dtype('int64')

In [46]:
dataset['Runs'].unique()

array([18426, 14255, 11370, 11363, 10889, 10773,  9378,  8701,  8273,
        6793,  5615,  5359,  5238,  4413,  4091,  3783,  3508,  3108,
        3092,  2962,  2917,  2818,  2806,  2753,  2477,  2338,  1994,
        1924,  1904,  1858,  1752,  1694,  1544,  1389,  1272,  1269,
        1237,  1230,  1005,   938,   934,   933,   883,   871,   867,
         858,   810,   792,   783,   773,   736,   707,   646,   629,
         617,   584,   566,   563,   552,   513,   510,   457,   456,
         439,   424,   401,   373,   362,   351,   339,   329,   310,
         292,   290,   287,   280,   269,   256,   243,   230,   225,
         223,   221,   218,   216,   207,   203,   193,   189,   180,
         176,   165,   163,   158,   153,   151,   149,   141,   136,
         132,   131,   130,   126,   122,   120,   118,   116,   115,
         114,   107,   104,   100,    93,    91,    90,    88,    86,
          81,    79,    77,    74,    73,    72,    68,    55,    54,
          52,    51,

In [47]:
dataset['Gender'].isna().sum()

np.int64(0)

In [48]:
dataset['Gender'].value_counts()

Gender
Men      236
Women    135
Name: count, dtype: int64

In [49]:
dataset.columns

Index(['PlayerName', 'Matches', 'Innings', 'Average', 'StrikeRate',
       'HighestScore', '4s', '6s', '50s', '100s', 'Runs', 'Gender'],
      dtype='object')

In [50]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 371 entries, 0 to 371
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PlayerName    371 non-null    object 
 1   Matches       371 non-null    int64  
 2   Innings       371 non-null    int64  
 3   Average       371 non-null    float64
 4   StrikeRate    322 non-null    float64
 5   HighestScore  371 non-null    int64  
 6   4s            254 non-null    Int64  
 7   6s            154 non-null    Int64  
 8   50s           371 non-null    int64  
 9   100s          371 non-null    int64  
 10  Runs          371 non-null    int64  
 11  Gender        371 non-null    object 
dtypes: Int64(2), float64(2), int64(6), object(2)
memory usage: 38.4+ KB


In [51]:
dataset.columns

Index(['PlayerName', 'Matches', 'Innings', 'Average', 'StrikeRate',
       'HighestScore', '4s', '6s', '50s', '100s', 'Runs', 'Gender'],
      dtype='object')

In [52]:
#completeed cleaning missing values(like ,'-',whitepaces,etc)
#completeed changing dattype of object to with respective to which fit for those columns

In [53]:
dataset.isna().sum() #claened invalid entries(Strikerate there are some nan they cant be putten zero)

PlayerName        0
Matches           0
Innings           0
Average           0
StrikeRate       49
HighestScore      0
4s              117
6s              217
50s               0
100s              0
Runs              0
Gender            0
dtype: int64

In [54]:
dataset

PlayerName  Matches  Innings  Average  StrikeRate  HighestScore  \
0     Sachin Tendulkar      463      452    44.83       86.23           200   
1          Virat Kohli      305      293    57.71       93.26           183   
2         Rohit Sharma      276      268    49.22       92.66           264   
3       Sourav Ganguly      311      300    41.02       73.70           183   
4         Rahul Dravid      344      318    39.16       71.23           153   
..                 ...      ...      ...      ...         ...           ...   
367  Bindeshwari Goyal        4        1     0.00       25.00             1   
368   Samantha Lobatto        3        2     0.00       12.50             1   
369      Anjali Sharma        3        3     0.33         NaN             1   
370         Rita Patel        1        1     1.00         NaN             1   
371      Manju Nadgoda        1        1     1.00        7.69             1   

       4s    6s  50s  100s   Runs Gender  
0    2016   195   96    49  18426    Men  
1    1332   152   75    51  14255    Men  
2    1066   349   59    33  11370    Men  
3    1122   190   72    22  11363    Men  
4     950    42   83    12  10889    Men  
..    ...   ...  ...   ...    ...    ...  
367  <NA>  <NA>    0     0      1  Women  
368  <NA>  <NA>    0     0      1  Women  
369  <NA>  <NA>    0     0      1  Women  
370  <NA>  <NA>    0     0      1  Women  
371  <NA>  <NA>    0     0      1  Women  

[371 rows x 12 columns]

In [55]:
# Step 7: Save it again
dataset.to_csv("CombinedcleanedOdiStats.csv", index=False)